{{ if .Values.ingresses }}

{{ range $ingress := .Values.ingresses }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $.Release.Name }}-{{ $ingress.name }}-ing
  namespace: {{ $.Release.Namespace }}
spec:
  ingressClassName: {{ $ingress.class | default "nginx" }}
  tls:
  - hosts:
      {{- range $rule := $ingress.rules }}
      - {{ $rule.host }}
      {{- end }}
    secretName: {{ $.Release.Name }}-{{ $ingress.tls }}-secret
  rules:
  {{- range $rule := $ingress.rules }}
  - host: {{ $rule.host }}
    http:
      paths:
      {{- range $path := $rule.paths }}
      - path: {{ $path.path }}
        pathType: {{ $path.type | default "Prefix" }}
        backend:
          service:
            name: {{ $.Release.Name }}-{{ $path.svc }}-svc
            port:
              number: {{ $path.port }}
      {{ end }}
  {{ end }}
---
{{ end }}

{{ end }}
