{{ if .Values.pvcs }}

{{ range $pvc := .Values.pvcs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Release.Name }}-{{ $pvc.name }}-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  accessModes:
  - {{ $pvc.accessMode }}
  resources:
    requests:
      storage: {{ $pvc.size }}
  storageClassName: {{ $pvc.storageClass }}
---
{{ end }}

{{ end }}
