{{ if .Values.secrets }}

{{ range $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Release.Name }}-{{ $secret.name }}-secret
  namespace: {{ $.Release.Namespace }}
type: {{ $secret.type }}
data:
  {{- range $key, $val := $secret.data }}
  {{ $key }}: |
    {{ $val }}
  {{- end }}
---
{{- end -}}

{{ end }}
